### ISSUE TITLE
[SUGGESTION] Cherax pulcher crayfish and Cherax alyciae crayfish

### ISSUE THREAD

**Issue by Sunconure11** [Womp6/Womp-s-Crayfish-Mod-Issues#2]
These guys are basically eye-candy. Would fit into your crayfish mod, too.

Another relative you could add would be the common yabby.

**Comment by Womp6** [comment]
I will be sure to add them.  Also, I already added the common yabby.

**Comment by Womp6** [comment]
Adding them now, sorry it took so long.  An update should be released either later today or sometime tomorrow (5/13/23).  I hope you enjoy :)
