### ISSUE TITLE
I'm getting to much crayfish while fishing

### ISSUE THREAD

**Issue by Cape-City** [Womp6/Womp-s-Crayfish-Mod-Issues#3]
I love the bunch of variants, but it seems that there is a 50% chance getting a crayfish while fishing. 10-25% or a adjustable value within configfile where fantastic ;)

**Comment by Womp6** [comment]
Okay, I will adjust this in my 1.19.4 update which I plan on making soon.  If you would like me to also fix this in another version, please let me know.

**Comment by Cape-City** [comment]
Actually i'm stuck on 1.19.3 ans can't update due some missing major mod updates :/

**Comment by Womp6** [comment]
Okay, I will also fix it in 1.19.3

**Comment by Cape-City** [comment]
German translation, if you want ;)

{
    "item.crayfish.raw_crayfish": "Roher Flusskrebs",
    "item.crayfish.cooked_crayfish": "Gekochter Flusskrebs",
    "item.crayfish.crayfish": "Flusskrebs",
    "item.crayfish.clayfish": "Languste",
    "item.crayfish.raw_sapphire_crayfish": "Roher Saphirkrebs",
    "item.crayfish.sapphire_crayfish": "Saphirkrebs",
    "item.crayfish.cooked_sapphire_crayfish": "Gekochter Saphirkrebs",
    "item.crayfish.raw_louisiana_crayfish": "Roher Louisiana-Flusskrebs",
    "item.crayfish.louisiana_crayfish": "Louisiana-Flusskrebs",
    "item.crayfish.cooked_louisiana_crayfish": "Gekochter Louisiana-Flusskrebs",
    "item.crayfish.raw_white_tubercled_crayfish": "Roher weißer Knollenkrebs",
    "item.crayfish.white_tubercled_crayfish": "Weißer Knollenkrebs",
    "item.crayfish.cooked_white_tubercled_crayfish": "Gekochte weiße Knollenkrebse",
    "item.crayfish.raw_zebra_crayfish": "Roher Zebrakrebs",
    "item.crayfish.zebra_crayfish": "Zebrakrebs",
    "item.crayfish.cooked_zebra_crayfish": "Gekochter Zebrakrebs",
    "item.crayfish.raw_virile_crayfish": "Roher männlicher Flusskrebs",
    "item.crayfish.virile_crayfish": "männlicher Flusskrebs",
    "item.crayfish.cooked_virile_crayfish": "Gekochter männlicher Flusskrebs",
    "item.crayfish.raw_rusty_crayfish": "Roher rostiger Flusskrebs",
    "item.crayfish.rusty_crayfish": "Rostiger Flusskrebs",
    "item.crayfish.cooked_rusty_crayfish": "Gekochter rostiger Flusskrebs",
    "item.crayfish.raw_supernova_crayfish": "Roher Supernova-Krebs",
    "item.crayfish.supernova_crayfish": "Supernova-Krebs",
    "item.crayfish.cooked_supernova_crayfish": "Gekochter Supernova-Krebs",
    "item.crayfish.raw_signal_crayfish": "Roher Signalkrebs",
    "item.crayfish.signal_crayfish": "Signalkrebs",
    "item.crayfish.cooked_signal_crayfish": "Gekochter Signalkrebs",
    "item.crayfish.supercrayfish": "Superkrebs",
    "item.crayfish.raw_swamp_dwarf_crayfish": "Roher Sumpf-Zwergkrebs",
    "item.crayfish.swamp_dwarf_crayfish": "Sumpf-Zwergkrebs",
    "item.crayfish.cooked_swamp_dwarf_crayfish": "Gekochter Sumpf-Zwergkrebs",
    "item.crayfish.burnt_crayfish": "Verbrannter Flusskrebs",
    "item.crayfish.raw_australian_redclaw_crayfish": "Roher australischer Rotschuppenkrebs",
    "item.crayfish.australian_redclaw_crayfish": "Australischer Rotschuppenkrebs",
    "item.crayfish.cooked_australian_redclaw_crayfish": "Gekochter australischer Rotschuppenkrebs",
    "item.crayfish.raw_big_sandy_crayfish": "Roher großer Sandflusskrebs",
    "item.crayfish.big_sandy_crayfish": "Großer Sandflusskrebs",
    "item.crayfish.cooked_big_sandy_crayfish": "Gekochter großer Sandflusskrebs",
    "item.crayfish.gumbo": "Gumbo",
    "item.crayfish.crayfish_stew": "Flusskrebseintopf",
    "item.crayfish.light_crayfish_stew": "Leichter Flusskrebseintopf",
    "item.crayfish.crayfish_boil": "Flusskrebssuppe",
    "item.crayfish.diamond_crayfish": "Diamantener Flusskrebs",
    "item.crayfish.golden_crayfish": "Goldener Flusskrebs",
    "item.crayfish.raw_spinycheek_crayfish": "Roher Stachelwangenkrebs",
    "item.crayfish.spinycheek_crayfish": "Stachelwangenkrebs",
    "item.crayfish.cooked_spinycheek_crayfish": "Gekochter Langustenkrebs",
    "item.crayfish.raw_parkhill_prairie_crayfish": "Roher Parkhill-Prärie-Krebs",
    "item.crayfish.parkhill_prairie_crayfish": "Parkhill-Prärie-Krebs",
    "item.crayfish.cooked_parkhill_prairie_crayfish": "Gekochter Parkhill-Präriekrebs",
    "item.crayfish.raw_common_yabby_crayfish": "Roher gewöhnlicher Yabby-Krebs",
    "item.crayfish.common_yabby_crayfish": "Gewöhnlicher Yabby-Krebs",
    "item.crayfish.cooked_common_yabby_crayfish": "Gekochter normaler Yabby-Krebs",
    "item.crayfish.raw_nashville_crayfish": "Roher Nashville-Krebs",
    "item.crayfish.nashville_crayfish": "Nashville-Flusskrebs",
    "item.crayfish.cooked_nashville_crayfish": "Gekochter Nashville-Flusskrebs",
    "item.crayfish.crayfish_bucket": "Eimer mit Flusskrebsen",
    "item.crayfish.crayfish_spawn_egg": "Flusskrebs-Laich-Ei",
    "entity.crayfish.crayfish": "Flusskrebs",
    "entity.crayfish.crayfish.predefined.0": "Flusskrebs",
    "entity.crayfish.crayfish.predefined.1": "Goldmakrele",
    "entity.crayfish.crayfish.predefined.2": "Sapphire Flusskrebs",
    "entity.crayfish.crayfish.predefined.3": "Louisiana-Krebs",
    "entity.crayfish.crayfish.predefined.4": "Weißer Knollenkrebs",
    "entity.crayfish.crayfish.predefined.5": "Zebra-Krebs",
    "entity.crayfish.crayfish.predefined.6": "Männlicher Flusskrebs",
    "entity.crayfish.crayfish.predefined.7": "Rostiger Flusskrebs",
    "entity.crayfish.crayfish.predefined.8": "Supernova-Krebs",
    "entity.crayfish.crayfish.predefined.9": "Signalkrebs",
    "entity.crayfish.crayfish.predefined.10": "Sumpf-Zwergflusskrebs",
    "entity.crayfish.crayfish.predefined.11": "Australischer Rotschuppenkrebs",
    "entity.crayfish.crayfish.predefined.12": "Großer sandiger Flusskrebs",
    "entity.crayfish.crayfish.predefined.13": "Stachelwangen-Krebs",
    "entity.crayfish.crayfish.predefined.14": "Parkhill-Prärie-Krebs",
    "entity.crayfish.crayfish.predefined.15": "Gewöhnlicher Yabby-Krebs",
    "entity.crayfish.crayfish.predefined.16": "Nashville-Krebs",
    "entity.crayfish.crayfish.predefined.17": "Murray-Flusskrebs",
    "item.crayfish.raw_murray_crayfish": "Roher Murray-Flusskrebs",
    "item.crayfish.murray_crayfish": "Murray-Flusskrebs",
    "item.crayfish.cooked_murray_crayfish": "Gekochter Murray-Flusskrebs",
    "entity.crayfish.crayfish.predefined.18": "Tasmanischer Riesenkrebs",
    "item.crayfish.raw_tasmanian_giant_crayfish": "Roher tasmanischer Riesenkrebs",
    "item.crayfish.tasmanian_giant_crayfish": "Tasmanischer Riesenkrebs",
    "item.crayfish.cooked_tasmanian_giant_crayfish": "Gekochter tasmanischer Riesenkrebs",
    "entity.crayfish.crayfish.predefined.19": "Japanischer Flusskrebs",
    "item.crayfish.raw_japanese_crayfish": "Roher japanischer Flusskrebs",
    "item.crayfish.japanese_crayfish": "Japanischer Flusskrebs",
    "item.crayfish.cooked_japanese_crayfish": "Gekochter japanischer Flusskrebs",
    "entity.crayfish.crayfish.predefined.20": "Marmorierter Flusskrebs",
    "item.crayfish.raw_marbled_crayfish": "Roher marmorierter Flusskrebs",
    "item.crayfish.marbled_crayfish": "Marmorierter Flusskrebs",
    "item.crayfish.cooked_marbled_crayfish": "Gekochter marmorierter Flusskrebs",
    "entity.crayfish.crayfish.predefined.21": "Oranger Zwergflusskrebs",
    "item.crayfish.raw_orange_dwarf_crayfish": "Roher oranger Zwergflusskrebs",
    "item.crayfish.orange_dwarf_crayfish": "Oranger Zwergflusskrebs",
    "item.crayfish.cooked_orange_dwarf_crayfish": "Gekochter oranger Zwergflusskrebs",
    "itemGroup.crayfish.crayfish_group": "Womp's Crayfish Mod",
    "block.crayfish.crayfish_trap": "Flusskrebsfalle",
    "entity.minecraft.villager.crayfish_trapper": "Flusskrebsfalle",
    "item.crayfish.raw_slough_crayfish": "Roher Sumpfkrebs",
    "item.crayfish.slough_crayfish": "Sumpfkrebs",
    "item.crayfish.cooked_slough_crayfish": "Gekochter Sumpfkrebs",
    "entity.crayfish.crayfish.predefined.22": "Sumpfkrebs",
    "item.crayfish.raw_cave_crayfish": "Roher Höhlenkrebs",
    "item.crayfish.cave_crayfish": "Höhlenkrebs",
    "item.crayfish.cooked_cave_crayfish": "Gekochter Höhlenkrebs",
    "entity.crayfish.crayfish.predefined.23": "Höhlenkrebs",
    "item.crayfish.raw_noble_crayfish": "Roher Edelkrebs",
    "item.crayfish.noble_crayfish": "Edelkrebs",
    "item.crayfish.cooked_noble_crayfish": "Gekochter Edelkrebs",
    "entity.crayfish.crayfish.predefined.24": "Edelkrebs",
    "item.crayfish.raw_hairy_marron_crayfish": "Roher haariger Marronenkrebs",
    "item.crayfish.hairy_marron_crayfish": "Haariger Marronenkrebs",
    "item.crayfish.cooked_hairy_marron_crayfish": "Gekochter haariger Marronenkrebs",
    "entity.crayfish.crayfish.predefined.25": "Haariger Marronenkrebs"
  }

**Comment by Womp6** [comment]
Thank you! I will be sure to include this in the update too!

**Comment by Womp6** [comment]
I'm currently working on an update and I have fixed the fishing chances to around 20% and I have added the German translation.  An update for 1.19.3 should be released either in a few hours or tomorrow (5/13/23).  I hope you enjoy :)

**Comment by Cape-City** [comment]
Fantastic! The new fishing chance is more realistic! Thnx for the fast fix ;)
Here is the update for the german translation, including the 2 new crayfish variants:

{
    "item.crayfish.raw_crayfish": "Roher Flusskrebs",
    "item.crayfish.cooked_crayfish": "Gekochter Flusskrebs",
    "item.crayfish.crayfish": "Flusskrebs",
    "item.crayfish.clayfish": "Languste",
    "item.crayfish.raw_sapphire_crayfish": "Roher Saphirkrebs",
    "item.crayfish.sapphire_crayfish": "Saphirkrebs",
    "item.crayfish.cooked_sapphire_crayfish": "Gekochter Saphirkrebs",
    "item.crayfish.raw_louisiana_crayfish": "Roher Louisiana-Flusskrebs",
    "item.crayfish.louisiana_crayfish": "Louisiana-Flusskrebs",
    "item.crayfish.cooked_louisiana_crayfish": "Gekochter Louisiana-Flusskrebs",
    "item.crayfish.raw_white_tubercled_crayfish": "Roher weißer Knollenkrebs",
    "item.crayfish.white_tubercled_crayfish": "Weißer Knollenkrebs",
    "item.crayfish.cooked_white_tubercled_crayfish": "Gekochte weiße Knollenkrebse",
    "item.crayfish.raw_zebra_crayfish": "Roher Zebrakrebs",
    "item.crayfish.zebra_crayfish": "Zebrakrebs",
    "item.crayfish.cooked_zebra_crayfish": "Gekochter Zebrakrebs",
    "item.crayfish.raw_virile_crayfish": "Roher männlicher Flusskrebs",
    "item.crayfish.virile_crayfish": "männlicher Flusskrebs",
    "item.crayfish.cooked_virile_crayfish": "Gekochter männlicher Flusskrebs",
    "item.crayfish.raw_rusty_crayfish": "Roher rostiger Flusskrebs",
    "item.crayfish.rusty_crayfish": "Rostiger Flusskrebs",
    "item.crayfish.cooked_rusty_crayfish": "Gekochter rostiger Flusskrebs",
    "item.crayfish.raw_supernova_crayfish": "Roher Supernova-Krebs",
    "item.crayfish.supernova_crayfish": "Supernova-Krebs",
    "item.crayfish.cooked_supernova_crayfish": "Gekochter Supernova-Krebs",
    "item.crayfish.raw_signal_crayfish": "Roher Signalkrebs",
    "item.crayfish.signal_crayfish": "Signalkrebs",
    "item.crayfish.cooked_signal_crayfish": "Gekochter Signalkrebs",
    "item.crayfish.supercrayfish": "Superkrebs",
    "item.crayfish.raw_swamp_dwarf_crayfish": "Roher Sumpf-Zwergkrebs",
    "item.crayfish.swamp_dwarf_crayfish": "Sumpf-Zwergkrebs",
    "item.crayfish.cooked_swamp_dwarf_crayfish": "Gekochter Sumpf-Zwergkrebs",
    "item.crayfish.burnt_crayfish": "Verbrannter Flusskrebs",
    "item.crayfish.raw_australian_redclaw_crayfish": "Roher australischer Rotschuppenkrebs",
    "item.crayfish.australian_redclaw_crayfish": "Australischer Rotschuppenkrebs",
    "item.crayfish.cooked_australian_redclaw_crayfish": "Gekochter australischer Rotschuppenkrebs",
    "item.crayfish.raw_big_sandy_crayfish": "Roher großer Sandflusskrebs",
    "item.crayfish.big_sandy_crayfish": "Großer Sandflusskrebs",
    "item.crayfish.cooked_big_sandy_crayfish": "Gekochter großer Sandflusskrebs",
    "item.crayfish.gumbo": "Gumbo",
    "item.crayfish.crayfish_stew": "Flusskrebseintopf",
    "item.crayfish.light_crayfish_stew": "Leichter Flusskrebseintopf",
    "item.crayfish.crayfish_boil": "Flusskrebssuppe",
    "item.crayfish.diamond_crayfish": "Diamantener Flusskrebs",
    "item.crayfish.golden_crayfish": "Goldener Flusskrebs",
    "item.crayfish.raw_spinycheek_crayfish": "Roher Stachelwangenkrebs",
    "item.crayfish.spinycheek_crayfish": "Stachelwangenkrebs",
    "item.crayfish.cooked_spinycheek_crayfish": "Gekochter Langustenkrebs",
    "item.crayfish.raw_parkhill_prairie_crayfish": "Roher Parkhill-Prärie-Krebs",
    "item.crayfish.parkhill_prairie_crayfish": "Parkhill-Prärie-Krebs",
    "item.crayfish.cooked_parkhill_prairie_crayfish": "Gekochter Parkhill-Präriekrebs",
    "item.crayfish.raw_common_yabby_crayfish": "Roher gewöhnlicher Yabby-Krebs",
    "item.crayfish.common_yabby_crayfish": "Gewöhnlicher Yabby-Krebs",
    "item.crayfish.cooked_common_yabby_crayfish": "Gekochter normaler Yabby-Krebs",
    "item.crayfish.raw_nashville_crayfish": "Roher Nashville-Krebs",
    "item.crayfish.nashville_crayfish": "Nashville-Flusskrebs",
    "item.crayfish.cooked_nashville_crayfish": "Gekochter Nashville-Flusskrebs",
    "item.crayfish.crayfish_bucket": "Eimer mit Flusskrebsen",
    "item.crayfish.crayfish_spawn_egg": "Flusskrebs-Laich-Ei",
    "entity.crayfish.crayfish": "Flusskrebs",
    "entity.crayfish.crayfish.predefined.0": "Flusskrebs",
    "entity.crayfish.crayfish.predefined.1": "Goldmakrele",
    "entity.crayfish.crayfish.predefined.2": "Sapphire Flusskrebs",
    "entity.crayfish.crayfish.predefined.3": "Louisiana-Krebs",
    "entity.crayfish.crayfish.predefined.4": "Weißer Knollenkrebs",
    "entity.crayfish.crayfish.predefined.5": "Zebra-Krebs",
    "entity.crayfish.crayfish.predefined.6": "Männlicher Flusskrebs",
    "entity.crayfish.crayfish.predefined.7": "Rostiger Flusskrebs",
    "entity.crayfish.crayfish.predefined.8": "Supernova-Krebs",
    "entity.crayfish.crayfish.predefined.9": "Signalkrebs",
    "entity.crayfish.crayfish.predefined.10": "Sumpf-Zwergflusskrebs",
    "entity.crayfish.crayfish.predefined.11": "Australischer Rotschuppenkrebs",
    "entity.crayfish.crayfish.predefined.12": "Großer sandiger Flusskrebs",
    "entity.crayfish.crayfish.predefined.13": "Stachelwangen-Krebs",
    "entity.crayfish.crayfish.predefined.14": "Parkhill-Prärie-Krebs",
    "entity.crayfish.crayfish.predefined.15": "Gewöhnlicher Yabby-Krebs",
    "entity.crayfish.crayfish.predefined.16": "Nashville-Krebs",
    "entity.crayfish.crayfish.predefined.17": "Murray-Flusskrebs",
    "item.crayfish.raw_murray_crayfish": "Roher Murray-Flusskrebs",
    "item.crayfish.murray_crayfish": "Murray-Flusskrebs",
    "item.crayfish.cooked_murray_crayfish": "Gekochter Murray-Flusskrebs",
    "entity.crayfish.crayfish.predefined.18": "Tasmanischer Riesenkrebs",
    "item.crayfish.raw_tasmanian_giant_crayfish": "Roher tasmanischer Riesenkrebs",
    "item.crayfish.tasmanian_giant_crayfish": "Tasmanischer Riesenkrebs",
    "item.crayfish.cooked_tasmanian_giant_crayfish": "Gekochter tasmanischer Riesenkrebs",
    "entity.crayfish.crayfish.predefined.19": "Japanischer Flusskrebs",
    "item.crayfish.raw_japanese_crayfish": "Roher japanischer Flusskrebs",
    "item.crayfish.japanese_crayfish": "Japanischer Flusskrebs",
    "item.crayfish.cooked_japanese_crayfish": "Gekochter japanischer Flusskrebs",
    "entity.crayfish.crayfish.predefined.20": "Marmorierter Flusskrebs",
    "item.crayfish.raw_marbled_crayfish": "Roher marmorierter Flusskrebs",
    "item.crayfish.marbled_crayfish": "Marmorierter Flusskrebs",
    "item.crayfish.cooked_marbled_crayfish": "Gekochter marmorierter Flusskrebs",
    "entity.crayfish.crayfish.predefined.21": "Oranger Zwergflusskrebs",
    "item.crayfish.raw_orange_dwarf_crayfish": "Roher oranger Zwergflusskrebs",
    "item.crayfish.orange_dwarf_crayfish": "Oranger Zwergflusskrebs",
    "item.crayfish.cooked_orange_dwarf_crayfish": "Gekochter oranger Zwergflusskrebs",
    "itemGroup.crayfish.crayfish_group": "Womp's Crayfish Mod",
    "block.crayfish.crayfish_trap": "Flusskrebsfalle",
    "entity.minecraft.villager.crayfish_trapper": "Flusskrebsfalle",
    "item.crayfish.raw_slough_crayfish": "Roher Sumpfkrebs",
    "item.crayfish.slough_crayfish": "Sumpfkrebs",
    "item.crayfish.cooked_slough_crayfish": "Gekochter Sumpfkrebs",
    "entity.crayfish.crayfish.predefined.22": "Sumpfkrebs",
    "item.crayfish.raw_cave_crayfish": "Roher Höhlenkrebs",
    "item.crayfish.cave_crayfish": "Höhlenkrebs",
    "item.crayfish.cooked_cave_crayfish": "Gekochter Höhlenkrebs",
    "entity.crayfish.crayfish.predefined.23": "Höhlenkrebs",
    "item.crayfish.raw_noble_crayfish": "Roher Edelkrebs",
    "item.crayfish.noble_crayfish": "Edelkrebs",
    "item.crayfish.cooked_noble_crayfish": "Gekochter Edelkrebs",
    "entity.crayfish.crayfish.predefined.24": "Edelkrebs",
    "item.crayfish.raw_hairy_marron_crayfish": "Roher haariger Marronenkrebs",
    "item.crayfish.hairy_marron_crayfish": "Haariger Marronenkrebs",
    "item.crayfish.cooked_hairy_marron_crayfish": "Gekochter haariger Marronenkrebs",
    "entity.crayfish.crayfish.predefined.25": "Haariger Marronenkrebs"
    "item.crayfish.raw_thunderbolt_crayfish": "Roher Donnerkeilkrebs",
    "item.crayfish.cooked_thunderbolt_crayfish": "Gekochter Donnerkeilkrebs",
    "item.crayfish.thunderbolt_crayfish": "Donnerkeilkrebs",
    "entity.crayfish.thunderbolt_crayfish": "Donnerkeilkrebs",
    "entity.crayfish.crayfish.predefined.26": "Donnerkeilkrebs",
    "item.crayfish.raw_blue_kong_crayfish": "Roher blauer Kong-Krebs",
    "item.crayfish.cooked_blue_kong_crayfish": "Gekochter blauer Kong-Krebs",
    "item.crayfish.blue_kong_crayfish": "Blauer Kong-Krebs",
    "entity.crayfish.blue_kong_crayfish": "Blauer Kong-Krebs",
    "entity.crayfish.crayfish.predefined.27": "Blauer Kong-Krebs"
  }

**Comment by Womp6** [comment]
Thank you! I will add this now
